pipeline {
    agent {label 'linux'}
    stages {
        stage('Read-Artifact') {
            steps {
                copyArtifacts projectName: 'create-artifact',
                    filter: 'report.txt',
                    fingerprintArtifacts: true,
                    selector: lastSuccessful()
            }
        }
    }
}
